"""Build reviewed Colab entry points from UI templates and immutable module pins."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TEMPLATES = ROOT / "notebooks"


def setup(commit):
    modules = {
        p.name: hashlib.sha256(p.read_bytes()).hexdigest() for p in sorted(ROOT.glob("zmo_*.py"))
    }
    dependencies = tomllib.loads((ROOT / "pyproject.toml").read_text())["project"]["dependencies"]
    lock = (ROOT / "requirements-dev.lock").read_text()
    return f"""# Generated by scripts/build_notebooks.py. Review changes in the module sources.
import hashlib
import importlib
import os
import sys
import tempfile
import urllib.request
from html import escape
from pathlib import Path

# Dependencies and all executable modules belong to the same reviewed release.
Path("/tmp/zmo-constraints.txt").write_text({lock!r}, encoding="utf-8")
%pip install -q -c /tmp/zmo-constraints.txt {" ".join(repr(d) for d in dependencies)}
HELPER_COMMIT = {commit!r}
HELPER_SHA256 = {modules["zmo_common.py"]!r}
MODULE_SHA256 = {modules!r}
release_dir = Path(tempfile.mkdtemp(prefix="zmo-release-" + HELPER_COMMIT + "-"))
for filename, expected in MODULE_SHA256.items():
    url = f"https://raw.githubusercontent.com/fmadore/zmo-ai-pipelines/{{HELPER_COMMIT}}/{{filename}}"
    with urllib.request.urlopen(url, timeout=60) as response:
        data = response.read()
    if hashlib.sha256(data).hexdigest() != expected:
        raise RuntimeError(f"Release verification failed for {{filename}}; get a fresh notebook")
    (release_dir / filename).write_bytes(data)
# Never reuse a module left in memory from another notebook release.
for filename in MODULE_SHA256:
    sys.modules.pop(filename[:-3], None)
sys.path.insert(0, str(release_dir))
importlib.invalidate_caches()
import zmo_common as zc
import zmo_transcribe as zt
import zmo_summary
import zmo_ocr
import zmo_audio
from zmo_notebook import NotebookSession
import ipywidgets as widgets
from openpyxl import load_workbook
from IPython.display import display, HTML, clear_output

"""


def build(commit=None, check=False):
    release = TEMPLATES / "release.json"
    if commit:
        if not re.fullmatch(r"[0-9a-f]{40}", commit):
            raise ValueError("Use a full immutable commit hash")
        if check:
            raise ValueError("--commit cannot be used with --check")
        release.write_text(json.dumps({"commit": commit}, indent=2) + "\n")
    commit = json.loads(release.read_text())["commit"]
    bootstrap = setup(commit)
    failures = []
    for template in sorted(TEMPLATES.glob("*.template.json")):
        notebook = json.loads(template.read_text())
        prefix = template.name.split("_")[0].lower()
        cells = notebook["cells"]
        cells[2]["source"] = (
            bootstrap + (TEMPLATES / f"{prefix}_setup.py.in").read_text()
        ).splitlines(True)
        cells[12]["source"] = (TEMPLATES / f"{prefix}_run.py.in").read_text().splitlines(True)
        cells[14]["source"] = ["session.recovery_panel()\n"]
        for cell in cells:
            if cell["cell_type"] == "code":
                cell["execution_count"] = None
                cell["outputs"] = []
        destination = ROOT / template.name.removesuffix(".template.json")
        output = json.dumps(notebook, ensure_ascii=False, indent=1) + "\n"
        if check:
            if not destination.exists() or destination.read_text() != output:
                failures.append(destination.name)
        else:
            destination.write_text(output)
    if failures:
        raise SystemExit("Regenerate notebooks: " + ", ".join(failures))


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--commit")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    build(args.commit, args.check)
